create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  theme text not null default 'dark',
  scale_name text not null default '4.2 Standard',
  prior_gpa numeric,
  prior_credits numeric,
  updated_at timestamptz not null default now()
);

create table if not exists public.semester_records (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  local_id text not null,
  name text not null,
  weight numeric not null default 1,
  order_index integer not null default 0,
  updated_at timestamptz not null default now(),
  unique (user_id, local_id)
);

create table if not exists public.course_records (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  semester_id bigint not null references public.semester_records(id) on delete cascade,
  local_id text not null,
  name text not null,
  credits numeric not null default 3,
  grade text not null,
  order_index integer not null default 0,
  updated_at timestamptz not null default now(),
  unique (user_id, local_id)
);

alter table public.profiles enable row level security;
alter table public.semester_records enable row level security;
alter table public.course_records enable row level security;

drop policy if exists "profiles are private" on public.profiles;
create policy "profiles are private" on public.profiles
  for all using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "semester records are private" on public.semester_records;
create policy "semester records are private" on public.semester_records
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "course records are private" on public.course_records;
create policy "course records are private" on public.course_records
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
